packages/express-cargo/src/binding.ts, packages/express-cargo/src/metadata.ts, packages/express-cargo/src/types.ts, packages/express-cargo/src/validator.ts
=> feat: validator

packages/express-cargo/src/binding.ts, packages/express-cargo/src/types.ts
binding 단계에서 발생한 에러를 모두 모아 에러미들웨어로 전달합니다
=> feat: collect error for all field

packages/express-cargo/src/binding.ts, packages/express-cargo/src/metadata.ts, packages/express-cargo/src/source.ts
express-cargo 에 등록된 필드를 metadata 로 관리합니다
=> feat: save field list

.github/workflows/test.yaml, apps/example/.swcrc
=> chore: ci test

packages/express-cargo/src/validator.ts, packages/express-cargo/tests/validator/equal.test.ts
- 데코레이터를 추가했습니다.
- 테스트를 추가했습니다.
=> add equal decorator

README.ko.md, README.md
README 영문 버전을 추가합니다
기존 한글 버전은 README.ko.md 파일로 변경하며 영문 버전을 기본으로 사용합니다
=> docs: README (en)

packages/express-cargo/src/validator.ts, packages/express-cargo/tests/validator/prefix.test.ts, packages/express-cargo/tests/validator/suffix.test.ts
=> test: suffix, prefix decorator test

.github/workflows/deploy-npm.yaml, packages/express-cargo/package.json
npm 배포를 위한 github action 을 추가합니다
=> chore: github action to deploy npm

apps/example/src/routers/validator.ts
exmple app에 prefix, suffix validator에 대한 코드를 추가합니다.
=> feat: add prefix and suffix validator to exmple app

.github/workflows/deploy-docs.yaml
docs 배포를 main 브랜치에 머지했을때로 변경합니다
=> chore: deploy docs when code is pushed to main branch

apps/docs/package.json, apps/example/package.json, package.json, packages/express-cargo/package.json
=> release: v0.1.0

apps/docs/docusaurus.config.ts, apps/docs/i18n/en/docusaurus-theme-classic/footer.json
=> docs: update footer items

apps/docs/i18n/ko/docusaurus-theme-classic/footer.json
=> docs: add Korean translations for footer texts

packages/express-cargo/src/binding.ts, packages/express-cargo/src/metadata.ts
=> feat: type casting

packages/express-cargo/src/validator.ts, packages/express-cargo/tests/validator/validate.test.ts
유저가 원하는 validate 함수를 정의하는 validate decorator 를 추가합니다
=> feat: validate decorator

packages/express-cargo/src/validator.ts, packages/express-cargo/tests/validator/regexp.test.ts
=> feat: regexp decorator

apps/example/src/app.ts, apps/example/src/routers/transform.ts
example app에 transform 예시를 추가합니다.
=> feat: transform example

packages/express-cargo/src/binding.ts, packages/express-cargo/src/metadata.ts, packages/express-cargo/src/transform.ts, packages/express-cargo/tests/transform/virtual.test.ts
=> feat: add virtual decorator

apps/example/src/routers/transform.ts, apps/example/src/routers/validator.ts, packages/express-cargo/src/validator.ts
validate decorator 의 example 을 추가합니다
=> feat: validate example

apps/example/src/routers/validator.ts
=> feat: regexp example

apps/example/src/routers/transform.ts
=> feat: add request example

apps/example/src/routers/transform.ts
virtual decorator exmple을 추가합니다.
=> feat: add virtual example

apps/example/src/app.ts
기존에 디테일한 에러메시지가 보이지 않던 부분을 수정했습니다.
=> refactor: update error handler to show detail message

apps/example/src/app.ts, apps/example/src/routers/classFieldInheritance.ts
=> feat: add example app for nested and interitance class test

packages/express-cargo/src/binding.ts, packages/express-cargo/src/metadata.ts, packages/express-cargo/src/transform.ts
- request와 virtual field를 각각 구분하여 별도의 fieldlList로 관리합니다.
=> feat: manage a list of transform fields using metadata

README.ko.md, README.md, apps/docs/docs/quick-start.md, apps/docs/src/pages/index.tsx
readme 와 dcos 의 기본 example 코드를 수정합니다
=> docs: update main example code

apps/docs/docusaurus.config.ts, apps/docs/i18n/en/docusaurus-theme-classic/footer.json, apps/docs/i18n/ko/docusaurus-theme-classic/footer.json
copyright 의 Inc 를 team 으로 수정합니다
=> docs: edit copyright

packages/express-cargo/src/binding.ts, packages/express-cargo/src/types.ts, packages/express-cargo/src/validator.ts, packages/express-cargo/tests/validator/equal.test.ts, packages/express-cargo/tests/validator/isFalse.test.ts, packages/express-cargo/tests/validator/isTrue.test.ts, packages/express-cargo/tests/validator/length.test.ts, packages/express-cargo/tests/validator/max.test.ts, packages/express-cargo/tests/validator/maxLength.test.ts, packages/express-cargo/tests/validator/min.test.ts, packages/express-cargo/tests/validator/minLength.test.ts, packages/express-cargo/tests/validator/notEqual.test.ts, packages/express-cargo/tests/validator/oneOf.test.ts, packages/express-cargo/tests/validator/prefix.test.ts, packages/express-cargo/tests/validator/range.test.ts, packages/express-cargo/tests/validator/regexp.test.ts, packages/express-cargo/tests/validator/suffix.test.ts, packages/express-cargo/tests/validator/validate.test.ts
validation 실패시 메시지를 원하는 대로 지정할수 있도록 합니다
=> feat: custom error message

apps/example/src/app.ts, apps/example/src/routers/arrayField.ts
=> feat: add array example

package.json
=> chore: engine version v20

apps/docs/docs/advanced/array-decorator.md, apps/docs/i18n/ko/docusaurus-plugin-content-docs/current/advanced/array-decorator.md, apps/docs/sidebars.ts
=> docs: add array decorator guide document

apps/docs/docs/advanced/default.md, apps/docs/i18n/ko/docusaurus-plugin-content-docs/current/advanced/default.md, apps/docs/sidebars.ts
=> docs: add docs for default value

apps/docs/package.json, apps/example-cjs/package.json, apps/example/package.json, package.json, packages/express-cargo/package.json
=> release: v0.3.0
